import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import PointOfSale from "../components/PointOfSale";

const Home: NextPage = () => {
    return (
        <Flex width="100%" height="100%">
            <Head>
                <title>Juniverse POS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <PointOfSale />
        </Flex>
    );
};

export default Home;
